### ISSUE TITLE
机器人转发的动态，只转发了九宫格图片中的第一张图

### ISSUE THREAD

**Issue by Airoof** [keithfeng425/Bilibili-QQ-BOT#1]
非常感谢 @keithfeng425 的无私分享，提供了一个好用的工具
我使用自己的QQ号，按照README的简介，完成了步骤1、2、4、5的简单设置
目前是在Win10上，用Terminal使用Bilibili-QQ-BOT-1.5这个版本进行配置

目前遇到了一个小问题：
主播发布的动态含有9张图片，是一个 文字+九宫格 图片形式的，如下图
![image](https://github.com/keithfeng425/Bilibili-QQ-BOT/assets/46644958/56fa36d9-aead-4a70-bfdb-c0c42326147f)

但机器人转发到QQ群中的动态，只有 完整的文字+九宫格图片中的第一张，如下图
![image](https://github.com/keithfeng425/Bilibili-QQ-BOT/assets/46644958/b304cfc9-e140-4d7e-9ebe-ddcb66323c9d)

请问，能不能把9张图都在QQ的动态转发中显示全呢，是不是我哪里没有设置正确，麻烦解答了，感谢感谢！

**Comment by keithfeng425** [comment]
你好，感谢你的使用与认可！目前我写的版本确实是只截取了动态的第一张图片，我这边尽快更新下版本！但是如果是这种九宫格切图的话，在QQ中可能显示效果也不会很好，这个由于本人目前技术力有限，可能要查询一下有没有好的开源工具能解决这一问题，呈现出更好的效果

**Comment by Airoof** [comment]
> 你好，感谢你的使用与认可！目前我写的版本确实是只截取了动态的第一张图片，我这边尽快更新下版本！但是如果是这种九宫格切图的话，在QQ中可能显示效果也不会很好，这个由于本人目前技术力有限，可能要查询一下有没有好的开源工具能解决这一问题，呈现出更好的效果

非常感谢及时回复
已经很好用了，期待功能完善，感谢无私分享！

**Comment by keithfeng425** [comment]
采纳了你的建议并对动态中的图片进行拼接处理，目前由于我的QQ号都被tx列入风控了，所以没办法实际测试效果，希望它可以在你的电脑上好用！更新地址：https://github.com/keithfeng425/Bilibili-QQ-BOT/releases/tag/1.7

**Comment by Airoof** [comment]
> 采纳了你的建议并对动态中的图片进行拼接处理，目前由于我的QQ号都被tx列入风控了，所以没办法实际测试效果，希望它可以在你的电脑上好用！更新地址：https://github.com/keithfeng425/Bilibili-QQ-BOT/releases/tag/1.7

万分感谢，更新非常及时，很给力，会在后面主播再次发9图的时候测试一下感谢感谢🤝
