### ISSUE TITLE
求助：1.5版本中，如何同时在2个qq群中推送消息

### ISSUE THREAD

**Issue by Airoof** [keithfeng425/Bilibili-QQ-BOT#3]
不好意思我太菜了。。在1.5版本成功完成配置后，可以完成一个qq群的消息推送
现在想同时在2个qq中实现软件的推送功能，尝试了修改**application.yml**文件中bilibili-group的参数

参考了一些其它bot的设置方法，把参数从
group： 92839547
改成了
group： 92839547 836596568
上述两串数字的位置是2个qq群的号码，但是没法成功推送消息T T

想问一下正确的设置应该是怎么样的，感谢感谢！

**Comment by Airoof** [comment]
顺便还想问一下，如何配置成
开播的时候@全体成员，下播和动态不@全体成员，感谢感谢！

（不太熟悉是不是可以一个issue里提两个问题，如果不可以的话我可以删掉这条消息，再单开一个

**Comment by keithfeng425** [comment]
目前你提到的两个功能点确实都没有，之前写这个只是给自己用，所以没考虑到多群推送以及各种配置项，之后的版本会尽可能追加这些功能的，谢谢支持！

**Comment by Airoof** [comment]
非常感谢！

**Comment by keithfeng425** [comment]
功能已更新，在application.yml中用半角逗号分隔多个群号即可
https://github.com/keithfeng425/Bilibili-QQ-BOT/releases/tag/2.1
