### ISSUE TITLE
关于步骤5和7如何完成

### ISSUE THREAD

**Issue by B5424** [keithfeng425/Bilibili-QQ-BOT#4]
您好，作者大大，这个第5和7怎么完成？作为小白我看了别人的问题终于做到第6步了，请问下我这是成功还是失败了？
![5da3a7ba40ac7361c642235f6702c716](https://github.com/user-attachments/assets/fc05d241-3097-4d4f-8794-68ac81175519)
![95dd63f21aff98f039ccbd544a24f99f](https://github.com/user-attachments/assets/b50977b2-1692-4365-8917-400602468043)
![7757e9d6aade3d95c20c7566e8641444](https://github.com/user-attachments/assets/7701a258-74a0-452b-800d-ba2d467d0564)

**Comment by keithfeng425** [comment]
这个项目我忘记写停止维护了😂 主要是协议一直被TX官方禁掉，所以使用的协议框架也就基本都停止维护了，抱歉抱歉
